blank_issues_enabled: true
contact_links:
  - name: Sriicoin Core Security Policy
    url: https://github.com/sriicoin/sriicoin/blob/master/SECURITY.md
    about: View security policy
  - name: Sriicoin Core Developers
    url: https://sriicoin.in
    about: Sriicoin Core homepage
